name: Release
on:
  push:
    tags:
    - '[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+'
    branches:
    - 'patch/ci-release-*'
    - 'main'
  pull_request:
    paths:
    - '.github/workflows/release.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

env:
  # Preview mode: Publishes the build output as a CI artifact instead of creating
  # a release, allowing for manual inspection of the output. This mode is
  # activated if the CI run was triggered by events other than pushed tags, or
  # if the repository is a fork.
  preview: ${{ !startsWith(github.ref, 'refs/tags/') || github.repository != 'ci-prebuild/helix' }}

jobs:
  build:
    name: Build ${{ matrix.build }}
    env:
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # don't fail other jobs if one fails
      matrix:
        build: [amd64, arm64]
        include:
        - build: amd64
          # WARN: When changing this to a newer version, make sure that the GLIBC isnt too new, as this can cause issues
          # with portablity on older systems that dont follow ubuntus more rapid release cadence.
          os: ubuntu-22.04
          rust: stable
        - build: arm64
          # Version should be kept in lockstep with the x86_64 version
          os: ubuntu-22.04-arm
          rust: stable

    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
        with:
          repository: "helix-editor/helix"
          ref: "14d6bc0febed9c692048271a8ae2362ac969c6e0"

      # The rust-toolchain action ignores rust-toolchain.toml files.
      # Removing this before building with cargo ensures that the rust-toolchain
      # is considered the same between installation and usage.
      - name: Remove the rust-toolchain.toml file
        run: rm rust-toolchain.toml

      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@fa04a1451ff1842e2626ccb99004d0195b455a88 # master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Show command used for Cargo
        run: |
          echo "target flag is: ${{ env.TARGET_FLAGS }}"

      - name: Fetch tree-sitter grammars
        run: cargo run --package=helix-loader --bin=hx-loader

      - name: Build release binary
        run: cargo build --profile opt --locked

        # Becuase otherwise taiki-e/install packages cargo-deb with
        # too new GLIBC version.
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install cargo-deb
        run: cargo binstall cargo-deb

      - name: Build ${{ matrix.build }}.deb
        shell: bash
        # if: matrix.build == 'x86_64-linux'
        run: |
          mkdir -p target/release
          cp target/opt/hx target/release/
          cargo deb --no-build --no-strip
          ls target/debian/

      - name: Upload ${{ matrix.build }}.deb to artifacts
        uses: actions/upload-artifact@v7
        if: env.preview == 'true'
        with:
          name: helix_25.7.1-1_${{ matrix.build }}.deb
          path: target/debian/helix_25.7.1-1_${{ matrix.build }}.deb
          archive: false

      - name: Upload ${{ matrix.build }}.deb to release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        if: env.preview == 'false'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/debian/helix_25.7.1-1_${{ matrix.build }}.deb
          tag: ${{ github.ref_name }}
          overwrite: true

      - name: Prepare dist for ${{ matrix.build }}.tar.xz
        shell: bash
        run: |
          mkdir -p dist
          cp "target/opt/hx" "dist/"
          if [ -d runtime/grammars/sources ]; then
            rm -rf runtime/grammars/sources
          fi
          cp -r runtime dist
          tar cJf helix-${{ matrix.build }}.tar.xz dist/*

      - name: Upload helix-${{ matrix.build }}.tar.xz to artifacts
        uses: actions/upload-artifact@v7
        if: env.preview == 'true'
        with:
          name: helix_25.7.1-1_${{ matrix.build }}.tar.xz
          path: helix-${{ matrix.build }}.tar.xz
          archive: false

      - name: Upload helix-${{ matrix.build }}.tar.xz to release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        if: env.preview == 'false'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: helix-${{ matrix.build }}.tar.xz
          tag: ${{ github.ref_name }}
          overwrite: true
